# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CRSTools
                                 A QGIS plugin
 Check, define and convert CRS v2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-05-25
        copyright            : (C) 2018 by Hieu Van
        email                : hieuvan@disroot.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

Phiên bản đã nâng cấp: dùng qgis.PyQt (chạy được trên PyQt5/QGIS 3 và
PyQt6/QGIS 4), bỏ resources.py (Qt5 rcc), bỏ các API đã bị gỡ.
"""
import os
import re

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QFileDialog, QTableWidgetItem

try:  # Qt6: QAction nằm trong QtGui
    from qgis.PyQt.QtGui import QAction
except ImportError:  # Qt5
    from qgis.PyQt.QtWidgets import QAction

from qgis.core import (
    Qgis,
    QgsProject,
    QgsVectorLayer,
    QgsVectorFileWriter,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
)

from .crs_tools_dialog import CRSToolsDialog
from .convertDialog import ConvertVN2000Dialog
from .checkDialog import CoordSysCheckerDialog
from .defineDialog import DefineDialog


# ---------------------------------------------------------------------------
# Khai báo hệ tọa độ (dạng dữ liệu, thay cho hàng trăm dòng if/elif)
# ---------------------------------------------------------------------------

# Kinh tuyến trục VN-2000 múi 3 độ
KTT_LIST = [102, 103, 104, 104.5, 104.75, 105, 105.5, 105.75, 106, 106.25,
            106.5, 107, 107.25, 107.5, 107.75, 108, 108.25, 108.5]

# 7 tham số chuyển đổi VN-2000 (hội nhập) -> WGS84
TOWGS84_HN = ("-191.90441429,-39.30318279,-111.45032835,"
              "0.00928836,-0.01975479,0.00427372,0.252906278")
TOWGS84_NB = "0,0,0,0,0,0,0"

PROJ_UTM_48 = "+proj=utm +zone=48 +datum=WGS84 +units=m +no_defs"
PROJ_UTM_49 = "+proj=utm +zone=49 +datum=WGS84 +units=m +no_defs"
PROJ_WGS84 = "+proj=longlat +datum=WGS84 +no_defs"


def _fmt(value):
    return "%g" % value


def vn2000_proj(lon_0, hoi_nhap=True):
    """Chuỗi PROJ của VN-2000 múi 3 độ, kinh tuyến trục lon_0."""
    return ("+proj=tmerc +lat_0=0 +lon_0=%s +k=0.9999 +x_0=500000 +y_0=0 "
            "+ellps=WGS84 +towgs84=%s +units=m +no_defs"
            % (_fmt(lon_0), TOWGS84_HN if hoi_nhap else TOWGS84_NB))


def proj_signature(proj):
    """Chuẩn hóa chuỗi PROJ thành 'chữ ký' để so sánh, không phụ thuộc thứ tự
    tham số hay các cờ phụ (+no_defs, +type=crs, +units=m...)."""
    params = {}
    for token in proj.split():
        if token.startswith('+'):
            key, _, val = token[1:].partition('=')
            params[key] = val
    if params.get('datum') == 'WGS84':
        params['ellps'] = 'WGS84'
    if 'k_0' in params:
        params['k'] = params.pop('k_0')

    items = []
    for key in ('proj', 'zone', 'lat_0', 'lon_0', 'k', 'x_0', 'y_0',
                'ellps', 'towgs84'):
        if key not in params:
            continue
        val = params[key]
        if key == 'towgs84':
            nums = [float(v) for v in val.split(',')]
            if all(abs(n) < 1e-12 for n in nums):
                continue  # towgs84 toàn 0 coi như không có
            items.append((key, tuple(round(n, 6) for n in nums)))
            continue
        try:
            num = round(float(val), 6)
        except ValueError:
            items.append((key, val))
            continue
        if key in ('lat_0', 'y_0') and num == 0:
            continue
        items.append((key, num))
    return tuple(items)


def _build_signature_table():
    table = {}
    for ktt in KTT_LIST:
        table[proj_signature(vn2000_proj(ktt, False))] = \
            "VN-2000 Noi bo KTT %s mui 3" % _fmt(ktt)
        table[proj_signature(vn2000_proj(ktt, True))] = \
            "VN-2000 Hoi nhap KTT %s mui 3" % _fmt(ktt)
    table[proj_signature(PROJ_UTM_48)] = "UTM Zone 48N - EPSG:32648"
    table[proj_signature(PROJ_UTM_49)] = "UTM Zone 49N - EPSG:32649"
    table[proj_signature(PROJ_WGS84)] = "WGS 84 Lat/Long - EPSG:4326"
    return table


SIGNATURES = _build_signature_table()


def crs_from_name(name, system_crs=None):
    """Chuyển tên hiển thị trong combobox thành QgsCoordinateReferenceSystem.

    Chấp nhận cả cách viết cũ ("EPSG"/"EPGS", "VN2000"/"VN-2000"...).
    Raise ValueError nếu không nhận diện được.
    """
    text = (name or '').strip()
    lower = text.lower()

    if lower == 'system':
        return system_crs

    if lower.startswith('utm'):
        m = re.search(r'zone\s*(\d+)', lower)
        if m:
            return QgsCoordinateReferenceSystem("EPSG:326%02d" % int(m.group(1)))

    if 'wgs' in lower:
        return QgsCoordinateReferenceSystem("EPSG:4326")

    if lower.replace('-', '').startswith('vn2000'):
        m = re.search(r'ktt\s*([\d.]+)', lower)
        if m:
            ktt = float(m.group(1))
            if ktt in KTT_LIST:
                hoi_nhap = not ('noi bo' in lower or 'nội bộ' in lower)
                crs = QgsCoordinateReferenceSystem.fromProj(
                    vn2000_proj(ktt, hoi_nhap))
                if crs.isValid():
                    return crs

    raise ValueError("Không nhận diện được hệ tọa độ: %s" % text)


class CheckDefConv:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.actions = []
        self.menu = self.tr(u'&Check, Defined and Convert CRS')

        # initialize locale
        locale_value = QSettings().value('locale/userLocale')
        locale = str(locale_value)[0:2] if locale_value else ''
        locale_path = os.path.join(
            self.plugin_dir, 'i18n', 'CheckDefConv_{}.qm'.format(locale))
        if locale and os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Tạo các dialog (gắn vào cửa sổ chính của QGIS) và nối signal MỘT lần
        parent = self.iface.mainWindow()
        self.dlg = CRSToolsDialog(parent)
        self.dlg1 = CoordSysCheckerDialog(parent)
        self.dlg2 = DefineDialog(parent)
        self.dlg3 = ConvertVN2000Dialog(parent)

        self.dlg.pushButton.clicked.connect(self.check)
        self.dlg.pushButton_2.clicked.connect(self.define)
        self.dlg.pushButton_3.clicked.connect(self.convert)
        self.dlg2.button_box.accepted.connect(self.apply_define)
        self.dlg3.lineEdit.clear()
        self.dlg3.toolButton.clicked.connect(self.select_output)

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        return QCoreApplication.translate('CheckDefConv', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True,
                   add_to_menu=True, add_to_toolbar=True, status_tip=None,
                   whats_this=None, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)
        if whats_this is not None:
            action.setWhatsThis(whats_this)
        if add_to_toolbar:
            self.iface.addToolBarIcon(action)
        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        # Icon nạp trực tiếp từ file (thay cho Qt resource ':/plugins/...')
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Kiểm tra, định nghĩa lại HTĐ, chuyển hệ tọa độ VN2000'),
            callback=self.run,
            parent=self.iface.mainWindow())

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)
        self.actions = []

    # ------------------------------------------------------------------ utils
    @staticmethod
    def _vector_layers():
        return [lyr for lyr in QgsProject.instance().mapLayers().values()
                if isinstance(lyr, QgsVectorLayer)]

    def _message(self, title, text, level=Qgis.MessageLevel.Info, duration=5):
        self.iface.messageBar().pushMessage(title, text, level=level,
                                            duration=duration)

    @staticmethod
    def find_crs(layer_object):
        """Trả về tên dễ nhớ của CRS (đặc biệt VN-2000 nội bộ / hội nhập)."""
        crs = layer_object.crs()
        if not crs.isValid():
            return "Unknown"
        return SIGNATURES.get(proj_signature(crs.toProj()), "Unknown")

    # ------------------------------------------------------------------ main
    def run(self):
        self.dlg.show()

    # ------------------------------------------------------------------ check
    def check(self):
        layers = list(QgsProject.instance().mapLayers().values())

        table = self.dlg1.tableWidget
        table.clear()
        table.setRowCount(len(layers))
        table.setColumnCount(2)
        table.setColumnWidth(0, 300)
        table.horizontalHeader().setStretchLastSection(True)
        table.setHorizontalHeaderItem(0, QTableWidgetItem("Layer name"))
        table.setHorizontalHeaderItem(1, QTableWidgetItem("CRS"))

        for row, layer in enumerate(layers):
            table.setItem(row, 0, QTableWidgetItem(layer.name()))
            table.setItem(row, 1, QTableWidgetItem(self.find_crs(layer)))

        self.dlg1.show()

    # ------------------------------------------------------------------ define
    def define(self):
        self.dlg2.listWidget.clear()
        self.dlg2.listWidget.addItems([layers.name() for layers in self._vector_layers()])
        self.dlg2.show()

    def apply_define(self):
        name = self.dlg2.comboBox.currentText()
        if name.strip().lower() == 'system':
            return
        try:
            crs = crs_from_name(name)
        except ValueError as err:
            self._message("Lỗi hệ tọa độ", str(err), Qgis.MessageLevel.Warning)
            return
        for layer in self._vector_layers():
            layer.setCrs(crs)

    # ------------------------------------------------------------------ convert
    def select_output(self):
        output_dir = QFileDialog.getExistingDirectory(
            self.dlg3, "Chọn thư mục để lưu", "")
        self.dlg3.lineEdit.setText(output_dir)

    def convert(self):
        self.dlg3.listWidget.clear()
        self.dlg3.listWidget.addItems([layers.name() for layers in self._vector_layers()])

        # PyQt6: exec_() đã bị gỡ, dùng exec()
        if self.dlg3.exec():
            output_dir = self.dlg3.lineEdit.text()
            if output_dir and os.path.isdir(output_dir):
                self.save_layers()
            else:
                self._message("Không có đường dẫn đến thư mục",
                              "Vui lòng chọn thư mục để lưu file",
                              Qgis.MessageLevel.Warning)

    def save_layers(self):
        if self.dlg3.checkBox_shp.isChecked():
            self.save_file('shp')
        if self.dlg3.checkBox_tab.isChecked():
            self.save_file('tab')

    def save_file(self, fmt):
        ext, driver = {'shp': ('.shp', 'ESRI Shapefile'),
                       'tab': ('.tab', 'MapInfo File')}[fmt]
        output_dir = self.dlg3.lineEdit.text()
        src_name = self.dlg3.comboBox.currentText()
        dst_name = self.dlg3.comboBox_output.currentText()
        os.makedirs(output_dir, exist_ok=True)

        project = QgsProject.instance()
        context = project.transformContext()

        for layer in self._vector_layers():
            try:
                # HTĐ đầu vào: định nghĩa lại CRS cho layer (nếu không phải System)
                if src_name.strip().lower() != 'system':
                    layer.setCrs(crs_from_name(src_name))
                dest_crs = crs_from_name(dst_name, layer.crs())
            except ValueError as err:
                self._message("Lỗi hệ tọa độ", str(err), Qgis.MessageLevel.Warning)
                return

            options = QgsVectorFileWriter.SaveVectorOptions()
            options.driverName = driver
            options.fileEncoding = 'UTF-8'
            if dest_crs.isValid() and dest_crs != layer.crs():
                options.ct = QgsCoordinateTransform(layer.crs(), dest_crs, project)

            safe_name = re.sub(r'[\\/:*?"<>|]', '_', layer.name())
            path = os.path.join(output_dir, safe_name + ext)

            # writeAsVectorFormat đã bị gỡ -> dùng writeAsVectorFormatV3
            result = QgsVectorFileWriter.writeAsVectorFormatV3(
                layer, path, context, options)
            error, error_msg = result[0], result[1]

            if error == QgsVectorFileWriter.WriterError.NoError:
                self._message("File được lưu:", "%s tại %s" % (safe_name + ext, output_dir),
                              Qgis.MessageLevel.Success, 2)
            else:
                self._message("Lỗi lưu file: %s" % (safe_name + ext), error_msg,
                              Qgis.MessageLevel.Warning, 5)
